export interface PremiumStyle {
  id: string;
  name: string;
  tag: string;
  fontFamily: string;
  fontSize: number;
  textColor: string;
  highlightColor: string;
  highlightBg?: string;
  stroke: string;
  animation: 'pop' | 'marker' | 'typewriter' | 'glow' | 'fade-slide' | 'bounce';
  description: string;
}

export const PREMIUM_STYLES: PremiumStyle[] = [
  // 🌟 Signature Presets
  {
    id: 'bumblebee',
    name: 'The Bumblebee',
    tag: 'MOST POPULAR',
    fontFamily: 'Anton',
    fontSize: 24,
    textColor: '#FFFFFF',
    highlightColor: '#FFE500',
    stroke: '3px #000000',
    animation: 'pop',
    description: 'Crisp white text with electric yellow punch words and dark stroke.',
  },
  {
    id: 'versely_neon',
    name: 'Versely Cyber Neon',
    tag: 'VERSELY.STUDIO',
    fontFamily: 'Outfit',
    fontSize: 24,
    textColor: '#FFFFFF',
    highlightColor: '#00F0FF',
    highlightBg: 'rgba(8,14,30,0.85)',
    stroke: 'none',
    animation: 'glow',
    description: 'Electric cyan glowing subtitle with dark frosted glass pill.',
  },
  {
    id: 'mrbeast',
    name: 'MrBeast Viral',
    tag: 'HIGH ENERGY',
    fontFamily: 'Anton',
    fontSize: 26,
    textColor: '#FFFFFF',
    highlightColor: '#10B981',
    stroke: '4px #000000',
    animation: 'bounce',
    description: 'Dynamic word scale with high-retention emerald highlights.',
  },
  {
    id: 'tidemark',
    name: 'Tidemark Marker',
    tag: 'CREATOR CLASSIC',
    fontFamily: 'Montserrat',
    fontSize: 22,
    textColor: '#FFFFFF',
    highlightColor: '#000000',
    highlightBg: '#A3E635',
    stroke: 'none',
    animation: 'marker',
    description: 'Clean typography with animated lime highlighter sweep.',
  },
  {
    id: 'versely_bold',
    name: 'Versely Bold Impact',
    tag: 'VERSELY.STUDIO',
    fontFamily: 'Bebas Neue',
    fontSize: 28,
    textColor: '#FFFFFF',
    highlightColor: '#F5C84B',
    highlightBg: 'rgba(0,0,0,0.9)',
    stroke: '3px #000000',
    animation: 'pop',
    description: 'Ultra-bold condensed typography with gold focus scale.',
  },
  {
    id: 'elevate',
    name: 'Elevate Luxury',
    tag: 'AESTHETIC',
    fontFamily: 'Playfair Display',
    fontSize: 22,
    textColor: '#F5E6C8',
    highlightColor: '#EAB308',
    stroke: 'none',
    animation: 'fade-slide',
    description: 'Champagne gold serif with smooth upward glide for storytelling.',
  },
  {
    id: 'versely_glow',
    name: 'Versely Aura Glow',
    tag: 'VERSELY.STUDIO',
    fontFamily: 'Poppins',
    fontSize: 23,
    textColor: '#FFFFFF',
    highlightColor: '#EC4899',
    highlightBg: 'rgba(24,12,38,0.85)',
    stroke: 'none',
    animation: 'glow',
    description: 'Neon magenta glowing text on dark purple translucent pill.',
  },
  {
    id: 'typewriter',
    name: 'Typewriter Clean',
    tag: 'MINIMAL',
    fontFamily: 'Courier Prime',
    fontSize: 20,
    textColor: '#FFFFFF',
    highlightColor: '#38BDF8',
    stroke: 'none',
    animation: 'typewriter',
    description: 'Monospace font with frame-accurate typewriter entrance.',
  },

  // 🚀 10 NEW PREMIUM CREATOR PRESETS
  {
    id: 'cyberpunk_glitch',
    name: 'Cyberpunk Neon 2077',
    tag: 'NEON NEW',
    fontFamily: 'Outfit',
    fontSize: 25,
    textColor: '#FCEE0A',
    highlightColor: '#00F0FF',
    highlightBg: 'rgba(10,10,20,0.92)',
    stroke: 'none',
    animation: 'glow',
    description: 'Cyberpunk neon yellow and cyan glow on obsidian glass pill.',
  },
  {
    id: 'hyper_red',
    name: 'Hyper Red Surge',
    tag: 'VIRAL SHORTS',
    fontFamily: 'Anton',
    fontSize: 26,
    textColor: '#FFFFFF',
    highlightColor: '#FF2A5F',
    stroke: '4px #000000',
    animation: 'pop',
    description: 'Stark white text with high-octane crimson red punch words.',
  },
  {
    id: 'emerald_beast',
    name: 'Emerald Luxe',
    tag: 'PREMIUM',
    fontFamily: 'Poppins',
    fontSize: 23,
    textColor: '#ECFDF5',
    highlightColor: '#10B981',
    highlightBg: 'rgba(6,78,59,0.85)',
    stroke: 'none',
    animation: 'bounce',
    description: 'Deep emerald glass pill with bright jade word highlights.',
  },
  {
    id: 'electric_violet',
    name: 'Electric Violet Aura',
    tag: 'PODCAST',
    fontFamily: 'Montserrat',
    fontSize: 24,
    textColor: '#FFFFFF',
    highlightColor: '#8B5CF6',
    highlightBg: 'rgba(30,15,50,0.85)',
    stroke: 'none',
    animation: 'glow',
    description: 'Ultra violet glowing text with soft purple backdrop.',
  },
  {
    id: 'sunset_glow',
    name: 'Sunset Coral',
    tag: 'CREATOR',
    fontFamily: 'Outfit',
    fontSize: 23,
    textColor: '#FFFFFF',
    highlightColor: '#000000',
    highlightBg: '#FF7E5F',
    stroke: 'none',
    animation: 'marker',
    description: 'Warm coral gradient highlighter sweep for engaging vlogs.',
  },
  {
    id: 'clean_minimal',
    name: 'Apple Minimalist',
    tag: 'CLEAN',
    fontFamily: 'Inter',
    fontSize: 22,
    textColor: '#FFFFFF',
    highlightColor: '#38BDF8',
    stroke: '2px rgba(0,0,0,0.8)',
    animation: 'fade-slide',
    description: 'Clean modern typography with sky blue active word glow.',
  },
  {
    id: 'tokyo_drift',
    name: 'Tokyo Drift Pink',
    tag: 'TIKTOK TREND',
    fontFamily: 'Bebas Neue',
    fontSize: 27,
    textColor: '#FFFFFF',
    highlightColor: '#FF007F',
    stroke: '3px #00F0FF',
    animation: 'pop',
    description: 'Vibrant hot pink pop text with cyan outline background.',
  },
  {
    id: 'golden_hour',
    name: 'Golden Hour Serif',
    tag: 'EDITORIAL',
    fontFamily: 'Playfair Display',
    fontSize: 23,
    textColor: '#FEF3C7',
    highlightColor: '#F59E0B',
    highlightBg: 'rgba(45,26,0,0.85)',
    stroke: 'none',
    animation: 'fade-slide',
    description: 'Rich amber gold serif text for luxury storytelling.',
  },
  {
    id: 'matrix_green',
    name: 'Matrix Code Green',
    tag: 'TECH',
    fontFamily: 'Courier Prime',
    fontSize: 21,
    textColor: '#22C55E',
    highlightColor: '#4ADE80',
    highlightBg: 'rgba(5,30,15,0.9)',
    stroke: 'none',
    animation: 'typewriter',
    description: 'Terminal green monospace text with hacker typewriter reveal.',
  },
  {
    id: 'frost_glass',
    name: 'Frosted Ice Blue',
    tag: 'MODERN',
    fontFamily: 'Poppins',
    fontSize: 23,
    textColor: '#E0F2FE',
    highlightColor: '#0284C7',
    highlightBg: 'rgba(12,44,75,0.85)',
    stroke: 'none',
    animation: 'marker',
    description: 'Cool frosted ice blue pill with oceanic highlight sweeps.',
  },
];
